cc_library(
    name = "test_steps",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.h"]),
    visibility = ["//visibility:public"],
    copts = ["-Werror"],
    deps = ["//test_utils", "//window", "//framework", "//core_messages", "//project"],
)
